[package]
name = "next-slide-please"
version = "0.1.0"
authors = ["lucas.jenss"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }
tungstenite = "0.11.1"
url = "2.2.0"
log = "0.4.0"
env_logger = "0.8.2"
webbrowser = "0.5.5"
reqwest = { version = "0.10.10", features = ["blocking", "json"] }
keybd_event = "0.1.2"
#iced = { version = "0.2",  features = ["tokio"] }
#iced_futures = "0.2"
#iced_native = "0.2"
#instant = "0.1.9"
